version: "2.2"

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      [
        'ES_JAVA_OPTS=-Xms2g -Xmx2g',
        'bootstrap.memory_lock=true',
        'discovery.type=single-node',
        'xpack.security.enabled=false',
        'xpack.security.enrollment.enabled=false'
      ]
    ports:
      - ${ES_PORT}:9200
    networks:
      - integration-be

volumes:
  certs:
    driver: local

networks:
  integration-be:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
